#!/usr/bin/env node
/**
 * prepare-client.mjs
 *
 * Runs before dev/build/typecheck (see package.json pre* hooks).
 * 1. Resolves the active client from SITE_ID (env or .env.local, defaults to kent).
 * 2. Generates src/generated/active-client.ts with a static import of that
 *    client's site.config.ts, so the bundler only ever includes ONE client.
 * 3. Copies clients/<id>/assets/ -> public/client/ (cleaned first) so images
 *    are served from a stable /client/... URL for the active client only.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const clientsDir = path.join(root, "clients");

function readEnvLocal(key) {
  const envFile = path.join(root, ".env.local");
  if (!fs.existsSync(envFile)) return undefined;
  for (const line of fs.readFileSync(envFile, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && m[1] === key) return m[2].replace(/^["']|["']$/g, "");
  }
  return undefined;
}

const soft = process.argv.includes("--soft");
const siteId = process.env.SITE_ID || readEnvLocal("SITE_ID") || "kent";
const clientDir = path.join(clientsDir, siteId);

if (!/^[a-z0-9_][a-z0-9-_]*$/.test(siteId)) {
  console.error(`✖ SITE_ID "${siteId}" is invalid. Use lowercase letters, numbers, hyphens.`);
  process.exit(1);
}
if (!fs.existsSync(path.join(clientDir, "site.config.ts"))) {
  if (soft) {
    console.warn(`⚠ prepare-client: no client "${siteId}" yet, skipping (postinstall).`);
    process.exit(0);
  }
  const available = fs.existsSync(clientsDir)
    ? fs
        .readdirSync(clientsDir)
        .filter((d) => fs.existsSync(path.join(clientsDir, d, "site.config.ts")))
    : [];
  console.error(
    `✖ No client found for SITE_ID="${siteId}" (expected clients/${siteId}/site.config.ts).\n` +
      (available.length ? `  Available clients: ${available.join(", ")}` : "  No clients exist yet.")
  );
  process.exit(1);
}

// 1. Generate the active-client module (gitignored).
const generatedDir = path.join(root, "src", "generated");
fs.mkdirSync(generatedDir, { recursive: true });
fs.writeFileSync(
  path.join(generatedDir, "active-client.ts"),
  `// AUTO-GENERATED by scripts/prepare-client.mjs. Do not edit, do not commit.
// Active client: ${siteId}
import config from "../../clients/${siteId}/site.config";

export const activeClient = config;
export const ACTIVE_CLIENT_ID = "${siteId}";
`
);

// 2. Sync assets -> public/client/ (active client only).
const assetsDir = path.join(clientDir, "assets");
const publicClientDir = path.join(root, "public", "client");
fs.rmSync(publicClientDir, { recursive: true, force: true });
fs.mkdirSync(publicClientDir, { recursive: true });
let assetCount = 0;
if (fs.existsSync(assetsDir)) {
  fs.cpSync(assetsDir, publicClientDir, { recursive: true });
  const countFiles = (dir) =>
    fs.readdirSync(dir, { withFileTypes: true }).reduce(
      (n, e) => n + (e.isDirectory() ? countFiles(path.join(dir, e.name)) : 1),
      0
    );
  assetCount = countFiles(publicClientDir);
}

console.log(`✔ Active client: ${siteId} (${assetCount} assets synced to public/client/)`);
